//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiterApp.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int ID { get; set; }
        public int orderID { get; set; }
        public int paidAmount { get; set; }
        public int paymentMethod { get; set; }
        public Nullable<decimal> discountAmount { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual order order { get; set; }
    }
}
