//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiterApp.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class takeAway
    {
        public int ID { get; set; }
        public int receiptID { get; set; }
        public string customerName { get; set; }
        public string customerSurname { get; set; }
        public string phoneNumber { get; set; }
        public string customerAdress { get; set; }
        public bool status { get; set; }
    
        public virtual receipt receipt { get; set; }
    }
}
