//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiterApp.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.receipts = new HashSet<receipt>();
        }
    
        public int ID { get; set; }
        public string profilePicture { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string eMail { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> registerDate { get; set; }
        public string phoneNumber { get; set; }
        public int roleID { get; set; }
        public bool status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<receipt> receipts { get; set; }
        public virtual role role { get; set; }
    }
}
